projects:
  graphqlApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: egs5gpovkza7bomj3pnhtoaqdy
      endpoints:
        prod: >-
          https://evfygqpzo5bfzph2gi6vctxi5a.appsync-api.us-east-1.amazonaws.com/graphql
